NumPy -> Numerical Python
    1.It is a open source library
    2.It will only work with homo geneous value 
    eg:{1,2,3,4,5}{0.1,0.2}
    3.It is very faster 
    Array -> hetero value {0.1,1,'string'} -> Slower 
    
    Install Numpy -> pip install numpy
    
    Understanding Data Types in Python
	Fixed-Type Arrays
	Arrays from Lists
	Arrays from Scratch

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
#Understanding Data Types in Python
import numpy as np
print(np.__version__)
#Array , list 
# creating from scrach
a=np.array([1,2,3,4,5,6,7])
print(a)

#Creating numpy Arrays from Lists
l=[5,6,7,8]
a1=np.array(l)
print(a1)
print(type(l))
print(type(a1))


1.23.5
[1 2 3 4 5 6 7]
[5 6 7 8]
<class 'list'>
<class 'numpy.ndarray'>


The Basics of NumPy Arrays	
    NumPy Array Attributes
	Array Indexing: Accessing Single Elements
	Array Slicing: Accessing Subarrays
	Reshaping of Arrays
	Array Concatenation
	Splitting
NumPy Universal Functions	
    Introducing UFuncs
	Exploring NumPy’s Ufuncs
	Advanced Ufunc Features
Aggregations	
    Min
	Max
	Summing the values in an Array

The Basics of NumPy Arrays	
    NumPy Array Attributes
	Array Indexing: Accessing Single Elements
	Array Slicing: Accessing Subarrays
	Reshaping of Arrays
	Array Concatenation
	Splitting

In [3]:
#Dimension in numpy array
import numpy as np
zd=np.array(60)
oneD=np.array([1,2,3,4,5])
twoD=np.array([[1,2,3],[4,5,6]])
ThreeD=np.array([[[1,2],[3,4]],[[5,6,],[7,8]]])
print(zd)
print(oneD)
print(twoD)
print(ThreeD)

60
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# NumPy Array Attributes
    #1.Determining the size 1d, 2d, 3d
    #2.Shape
    #3.Memory consumption
    #4.Data types
Att=np.array([[[1,2],[3,4]],[[5,6,],[7,8]]])
print(Att.ndim) # dimension
print(Att.shape) #shape --> dimesnion (2,2), count of value(2)
print(Att.size) #memory consumption
print(Att.dtype) #Data type


3
(2, 2, 2)
8
int32


In [8]:
#Array Indexing: Accessing Single Elements
oneD=np.array([1,2,3,4,5])
twoD=np.array([[1,2,3],[4,5,6]])
ThreeD=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(oneD[2]) # 1d
print(twoD[1,0]) #2d
print(ThreeD[1,1,1]) #3d accessing value 8
print(ThreeD[0,1,1]) #3d accessing value 4

3
4
8
4


In [14]:
#Array Slicing: Accessing Subarrays
#start =0 , stop : len of array
a1d=np.array([1,2,3,4,5,6,7])
#neglect the given index and print all prev value
print(a1d[:4])
print(a1d[4:]) #inclue the index and print until the len
print(a1d[2:5]) # include both index 
print(a1d[::2]) #Skip all 2nd value 
print(a1d[::-1]) #reverse the array

[1 2 3 4]
[5 6 7]
[3 4 5]
[1 3 5 7]
[7 6 5 4 3 2 1]


In [16]:
#Reshaping of Arrays
r=np.array([1,2,3,4,5,6])
print(r.shape)
print(r.reshape(3,2))

(6,)
[[1 2]
 [3 4]
 [5 6]]


In [19]:
#Array Concatenation
a1=np.array([1,2,3,4,5,6])
a2=np.array([7,8,9,10,11,12])
print(np.concatenate([a1,a2]))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [21]:
#Splitting
s=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ss=np.split(s,2)
print(ss[0])
print(ss[1])

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]


NumPy Universal Functions

Introducing UFuncs:
1.It will be using in math prblm
2.Characteristics:
    a.it will work with ndarray
    b.broadcasting
    c.arith, trig,stat, bit twiddling  
    
	
    
	Advanced Ufunc Features

In [22]:
#Exploring NumPy’s Ufuncs
    #Arithmetics :
    #np.add(a,b)
    #np.subtract(a,b)
    #np.multiply(a,b)
    #np.division(a,b)
    #np.floor_divide(a,b)
    #np.power(a,b)
    #np.mod(a,b)
    
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.floor_divide(a,b))
print(np.power(a,b))
print(np.mod(a,b))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0 0 0 0]
[    1    64  2187 65536]
[1 2 3 4]


Trignometric fn:
sin
cos
tan
arcsin ->inverse
arccos
arctan
hypot
sinh
cosh
tanh
arcsinh ->inverse
arccosh
arctanh
Conversion of rad to deg & deg to rad:
deg2rad
rad2deg


In [23]:
angles=np.array([0,30,45,60,90,180])
print(angles)
radians=np.deg2rad(angles)
print(radians)
sinval= np.sin(radians)
print(sinval)
print(np.cos(radians))
print(np.tan(radians))
print(np.arcsin(sinval))
print(np.arccos(np.cos(radians)))
print(np.arctan(np.tan(radians)))
print(np.hypot(4,3)) 
print(np.sinh(radians))
print(np.tanh(radians))
print(np.cosh(radians))
print(np.arcsinh(np.sinh(radians)))
print(np.arccosh(np.cosh(radians)))
print(np.arctanh(np.tanh(radians)))

[  0  30  45  60  90 180]
[0.         0.52359878 0.78539816 1.04719755 1.57079633 3.14159265]
[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]
[ 1.00000000e+00  8.66025404e-01  7.07106781e-01  5.00000000e-01
  6.12323400e-17 -1.00000000e+00]
[ 0.00000000e+00  5.77350269e-01  1.00000000e+00  1.73205081e+00
  1.63312394e+16 -1.22464680e-16]
[0.00000000e+00 5.23598776e-01 7.85398163e-01 1.04719755e+00
 1.57079633e+00 1.22464680e-16]
[0.         0.52359878 0.78539816 1.04719755 1.57079633 3.14159265]
[ 0.00000000e+00  5.23598776e-01  7.85398163e-01  1.04719755e+00
  1.57079633e+00 -1.22464680e-16]
5.0
[ 0.          0.54785347  0.86867096  1.24936705  2.3012989  11.54873936]
[0.         0.48047278 0.6557942  0.78071444 0.91715234 0.99627208]
[ 1.          1.14023832  1.32460909  1.60028686  2.50917848 11.59195328]
[0.         0.52359878 0.78539816 1.04719755 1.57079633 3.14159265]
[0.         0.52359878 0.78539816 1.04719755 1.57079633 3.14159265]